// ===== AUTO-GENERATED by casing/enclosure.py — DO NOT hand-edit; change the Python =====
part        = "assembly";   // assembly | tray | window2d | section   (-D 'part="tray"')
board_edge=160.000; board_th=1.600; patch_w=82.494; board_r=6.000;
hole_xy=72.000; clear=1.000; wall=4.000; floor_th=4.000;
standoff_h=6.000; air_gap=10.000; window_th=3.000; ext_r=10.000;
fillet=2.000; so_od=7.000; so_pilot=2.500;
gasket_inset=1.250; gasket_w=1.500; gasket_d=1.000;
lip_w=1.500; lip_h=2.000; win_clear=0.400;
sma_d=12.000; sma_z=10.800; web_floor=7.000; zip_d=3.500;
vent=true; vent_d=6.000; vent_seat_d=14.000; vent_x=50.000; vent_y=50.000;
ear_len=12.000; ear_w=30.000; ear_hole_d=4.500;
cav=162.000; ext=170.000; board_bot=10.000; board_top=11.600;
wall_top=21.600; lip_top=23.600; window=166.200;
lip_bevel=1.000; brand_size=6.000; brand_depth=0.600;
brand_l1="SPACEFLIGHT ROCKETRY GIESSEN"; brand_l2="869.525 MHz   RHCP";
deco_on=true; deco_sz=36.000; deco_svg="../archive/corner_deco.svg";
$fn=96;

module rrect(s, r) { offset(r = r) square(s - 2 * r, center = true); }
module rprism(s, r, h) { linear_extrude(height = h) rrect(s, max(0.01, r)); }

// four board standoff bosses (nylon M3 self-taps into the boss — no metal at/above the GP)
module standoffs() {
    for (sx = [-1, 1], sy = [-1, 1])
        translate([sx * hole_xy, sy * hole_xy, floor_th])
            difference() {
                union() {
                    cylinder(d = so_od, h = standoff_h);
                    cylinder(d1 = so_od + 2 * fillet, d2 = so_od, h = fillet);   // base fillet
                }
                translate([0, 0, -0.1]) cylinder(d = so_pilot, h = standoff_h + 0.2);  // self-tap pilot bore
            }
}

// foam-gasket groove (inboard) cut into the wall top; outer land stays flat for the adhesive bond
module gasket_groove() {
    inner = cav + 2 * gasket_inset;
    outer = cav + 2 * (gasket_inset + gasket_w);
    translate([0, 0, wall_top - gasket_d])
        linear_extrude(height = gasket_d + 0.1)
            difference() { rrect(outer, ext_r); rrect(inner, ext_r); }
}

// outer locating lip the acrylic window drops into (sets the air gap by a hard ledge; drip edge).
// The OUTER face tapers in (a bezel) for a finished look; the inner pocket wall stays vertical.
module window_lip() {
    translate([0, 0, wall_top])
        difference() {
            linear_extrude(height = lip_h, scale = (ext - 2 * lip_bevel) / ext) rrect(ext, ext_r);
            translate([0, 0, -0.1]) rprism(ext - 2 * lip_w, ext_r, lip_h + 0.2);
        }
}

// coax / SMA feed-through: teardrop (bridgeable crown) with a FLAT bottom >=3 mm above the floor
module sma_cut() {
    yb = -ext / 2 - 1; len = wall + 2;
    intersection() {
        hull() {
            translate([0, yb, sma_z]) rotate([-90, 0, 0]) cylinder(d = sma_d, h = len);
            translate([0, yb, sma_z + sma_d * 0.55]) rotate([-90, 0, 0]) cylinder(d = 0.8, h = len);
        }
        translate([-sma_d, yb - 1, web_floor]) cube([2 * sma_d, len + 2, ext]);   // flat bottom
    }
    // 2x zip-tie strain-relief holes flanking the bore
    for (sx = [-1, 1])
        translate([sx * (sma_d / 2 + zip_d), yb, sma_z]) rotate([-90, 0, 0]) cylinder(d = zip_d, h = len);
}

// breather vent (floor, off-corner, behind the GP -> RF-safe): through-hole + exterior patch seat
module vent_cut() {
    if (vent) {
        translate([vent_x, vent_y, -0.1]) cylinder(d = vent_d, h = floor_th + 0.2);
        translate([vent_x, vent_y, -0.1]) cylinder(d = vent_seat_d, h = 0.8);    // exterior patch recess
    }
}

// flat mount ears on +/-X (coplanar with the floor; outside the sealed cavity). The root EMBEDS
// 'ov' mm into the wall so the ear FUSES with the body -> ONE connected first-layer footprint
// (a touching-but-not-overlapping ear slices as separate islands).
module ears() {
    ov = 4;                 // overlap into the wall (wall is 4 mm -> embeds to the cavity inner face)
    L  = ear_len + ov;
    for (sx = [-1, 1])
        translate([sx * (ext / 2 + (ear_len - ov) / 2), 0, 0])
            difference() {
                linear_extrude(floor_th) offset(r = 3) square([L - 6, ear_w - 6], center = true);
                for (sy = [-1, 1])
                    translate([sx * (L / 2 - 4.5), sy * ear_w * 0.28, -0.1])
                        cylinder(d = ear_hole_d, h = floor_th + 0.2);
            }
}

// debossed branding on the +Y outer wall (two lines) — exterior only, shallow, watertight-safe.
// mirror() in X so it reads correctly when viewed from outside (+Y, looking -Y).
module branding() {
    zs = [[brand_l1, wall_top * 0.60], [brand_l2, wall_top * 0.34]];
    for (i = [0:1])
        translate([0, ext / 2 + 0.1, zs[i][1]])
            rotate([90, 0, 0])
                linear_extrude(height = brand_depth + 0.2)
                    mirror([1, 0, 0])
                        text(zs[i][0], size = brand_size, halign = "center", valign = "center",
                             font = "Liberation Sans:style=Bold");
}

// debossed sunburst (archive/corner_deco.svg) on the +X outer wall (faces +X, cuts -X into the wall)
module deco() {
    if (deco_on)
        translate([ext / 2 - brand_depth, 0, wall_top * 0.5])
            rotate([0, 90, 0])
                linear_extrude(height = brand_depth + 0.2)
                    resize([deco_sz, deco_sz, 0], auto = true) import(deco_svg, center = true);
}

module tray() {
    cr = max(0.01, ext_r - wall);
    difference() {
        union() {
            rprism(ext, ext_r, wall_top);
            window_lip();
            ears();
        }
        // cavity with a 45-ish inner floor/wall fillet at the base
        translate([0, 0, floor_th])
            linear_extrude(height = fillet, scale = cav / (cav - 2 * fillet)) rrect(cav - 2 * fillet, cr);
        translate([0, 0, floor_th + fillet]) rprism(cav, cr, wall_top);
        gasket_groove();
        sma_cut();
        vent_cut();
        branding();
        deco();
    }
    standoffs();
}

module window3d() { translate([0, 0, wall_top]) rprism(window, ext_r, window_th); }
module window2d() { rrect(window, ext_r); }   // undersized cut outline -> DXF (lip + clearance)

module board_ph() {
    color([0.0, 0.45, 0.2]) translate([0, 0, board_bot]) rprism(board_edge, board_r, board_th);
    color([0.85, 0.65, 0.1]) translate([0, 0, board_top]) rprism(patch_w, 6, 0.4);
}

module assembly() {
    tray();
    board_ph();
    color([0.6, 0.8, 1.0, 0.35]) window3d();
}

module section() {
    difference() {
        assembly();
        translate([-ext, 0, -60]) cube([2 * ext, 2 * ext, 220]);   // clean half-space: remove y>0
    }
}

if (part == "assembly") assembly();
else if (part == "tray") tray();
else if (part == "window2d") window2d();
else if (part == "section") section();
